@extends('frontend.layouts.app')

@section('title') KVKK - Kişisel Verileri Koruma Kanunu - {{ config('app.name') }} @endsection

@section('content')
    <div class="w100 sub-page-wrap">
        <div class="sub-hero"><img src="{{asset('/img/images/header-image.jpg')}}" alt="{{ config('app.name') }}" /></div>
        <div class="wrap">
            <div class="page-title page-title-left"><strong>KVKK</strong></div>
            <div class="page-about page-about-left">
                <p><strong>Verar Kargo L.T.D.</strong><br /><strong>KİŞİSEL VERİLERİN KORUNMASI VE İŞLENMESİ POLİTİKASI</strong></p>
                <p><br /><br /></p>
                <p><strong>1- GİRİŞ :</strong><br />Kişisel verilerin korunması, Verar Kargo L.T.D’nin (Kısaca “Verar Kargo”) Kurumsal anlamda önem verdiği Değer ve Politikalar arasındadır.</p>
                <p>İşbu Kişisel Verilerin Korunması ve İşlenmesi Politikası (Kısaca Politika), Verar Kargo’nun 6698 Sayılı Kişisel Verilerin Korunması Kanunu (“KVK Kanunu”) ve diğer ilgili mevzuat hükümleri uyarınca kişisel verilerin işlenmesi ve korunması konusunda benimsenecek ve uygulama noktasında dikkate alınacak ilkeleri ortaya koymaktadır.</p>
                <p>Bu Politika ile Verar Kargo ilişkili tüm şahıslara ait her türlü kişisel verinin 6698 sayılı Kişisel Verilerin Korunması Kanunu’na uygun olarak işlenerek, muhafaza edilmesi konusunda işbu Politika’ya ve buna bağlı olarak uygulanacak prosedürlere uygun davranmayı taahhüt eder.</p>
                <p><br /><br /></p>
                <p><strong>2- POLİTİKANIN AMACI :</strong><br />İşbu Politika’nın amacı, KVK Kanunu’na uyum için kişisel verilerin korunmasına yönelik yöntem ve süreçlere ilişkin esasları tespit etmektir.</p>
                <p>Bu kapsamda Verar Kargo kendi bünyesinde Politika’ya uyum için gerekli düzenlemeleri yapacak ve periyodik olarak uyum konusunda iç denetim mekanizmalarını işleterek Politika’ya uygunluğun devamlılığını sağlayacak ve kişisel verilerin işlenmesi ve korunması bakımından gerekli her türlü idari ve teknik tedbirleri alacaktır.</p>
                <p><br /><br /></p>
                <p><strong>3- POLİTİKANIN KAPSAMI :</strong><br />İşbu Politika, Verar Kargo’nun çalışanları, müşterileri, web sitesi ziyaretçileri, mobil uygulama kullanıcıları da dahil olmak üzere, Verar Kargo’nun faaliyetleri sırasında topladığı, işlediği yahut kendisi ile paylaşılan Kişisel Veri’leri kapsar, söz konusu faaliyetlere uygulanır ve KVK Düzenlemelerinin gerektirmesi halinde yahut Verar Kargo’nun veri sorumlusu temsilcisi yahut Komite’nin gerekli gördüğü hallerde, yönetim kurulu onayı ile değiştirilebilir.</p>
                <p><br /><br /></p>
                <p><strong>4- TANIMLAR :</strong><br />Kişisel Veri doğrudan veya dolaylı olarak Verar Kargo’nun bir İlgili Kişi’nin kimliğini, tek başına veya Verar Kargo’nun elindeki ya da kontrolündeki diğer bilgilerle birleştirerek belirlemesine imkân veren her türlü bilgi anlamına gelmektedir.<br />Özel Nitelikli Kişisel Veri kişilerin ırkı, etnik kökeni, siyasi düşüncesi, felsefi inancı, dini, mezhebi veya diğer inançları, kılık ve kıyafeti, dernek, vakıf ya da sendika üyeliği, sağlığı, cinsel hayatı, ceza mahkûmiyeti ve güvenlik tedbirleriyle ilgili bilgiler ile biyometrik ve genetik bilgileri ile ilgili veriler anlamına gelmektedir.<br />Kişisel Sağlık Verisi kimliği belirli veya belirlenebilir gerçek kişiye ilişkin her türlü sağlık bilgisi anlamına gelmektedir.<br />Veri İşleme Kişisel Veri’ler üzerinde gerçekleştirilen, toplama, kaydetme, depolama, muhafaza etme, değiştirme, yeniden düzenleme, açıklama, aktarma, devralma, elde edilebilir hale getirme, sınıflandırma ya da kullanılmasını engelleme de dahil her türlü işlem anlamına gelmektedir.<br />İlgili Kişi Kişisel Veri’leri Verar Kargo tarafından yahut adına işlenen tüm gerçek kişiler anlamına gelmektedir.<br />Açık Rıza belirli bir konu hakkında, bilgilendirildikten sonra, özgür iradeyle verilen onay anlamına gelmektedir.<br />İmha Kişisel Veri’lerin silinmesi veya yok edilmesi anlamına gelmektedir.<br />Anonim Hale Getirilmiş Veri, veri sorumlusu ya da İlgili Kişi’yi belirlenebilir hale getirecek başka herhangi bir kişi tüm makul ve olağan yöntemleri kullandıktan sonra dahi, Kişisel Veri’nin hiçbir surette kimliği belirli veya belirlenebilir bir gerçek kişiyle ilişkilendirilemeyecek hâle getirilmesi anlamına gelmektedir.<br />Veri İşleyen veri sorumlusunun verdiği yetkiye dayanarak onun adına Kişisel Veri’leri işleyen gerçek veya tüzel kişi anlamına gelmektedir. Her bir somut olayda Veri İşleyen’in kim olduğu ayrıca değerlendirilmelidir.<br />Veri Sorumlusu Kişisel Veri’lerin işleme amaçlarını ve vasıtalarını belirleyen, veri kayıt sisteminin kurulmasından ve yönetilmesinden sorumlu olan gerçek veya tüzel kişi anlamına gelmektedir. Veri sorumlusu Verar Kargo olabileceği gibi zaman zaman Verar Kargo adına yahut Verar Kargo’nun yetkilendirdiği üçüncü bir kişi de olabilir. Her bir somut olayda veri sorumlusunun kim olduğu ayrıca değerlendirilmelidir.<br />Kurul Kişisel Verileri Koruma Kurulu anlamına gelmektedir.</p>
                <p><br /><br /></p>
                <p><strong>5- KİŞİSEL VERİLERİN İŞLENMESİNDE UYGULANACAK İLKELER :</strong><br />Verar Kargo tarafından kişisel veriler sözlü, yazılı veya elektronik ortamda otomatik veya otomatik olmayan yöntemlerle işlenecek olup, kişisel verilerin işlenmesi hususunda Anayasa ve KVK Kanunu’na uygun şekilde hareket edilecektir.</p>
                <p>Ayrıca kişisel verilerin işlenmesinde bir takım ilkelere de sadık kalınacaktır. Bu bağlamda;</p>
                <p>a. Kişisel veriler, Verar Kargo tarafından hukuka ve dürüstlük kurallarına uygun hareket edilerek, orantılılık ve ölçülülük ilkeleri gereği, gerektiği kadar kişisel veriyi amacına uygun olarak işlenecektir.</p>
                <p>b. Kişisel veriler, Verar Kargo tarafından belirli, açık, meşru ve hukuka uygun amaçlarla işlenecektir. Verar Kargo, Veri Sahipleri’nin Kişisel Verilerinin elde edilmesinden önce kendilerine bu amaçları açıkça duyurmaktadır.</p>
                <p>c. Verar Kargo, kişisel verileri yalnızca kanunlarda öngörülen süreler ile veya işlendikleri amaca uygun olarak gerektiği kadar muhafaza eder. Bu kapsamda, ilgili mevzuatta kişisel verilerin saklanması için bir süre belirlenmişse bu süreye uygun davranılacak, bir süre belirlenmemişse, kişisel veriler işlendikleri amaç için gerekli olan süre kadar muhafaza edilecektir. Şu kadar ki, bu süre mevzuatta belirlenen yükümlülüklere uygun davranmak ya da meşru işletme menfaatlerini korumak amacıyla daha uzun süre tutulabilir.</p>
                <p>Verar Kargo, fiziksel ve elektronik veri kayıt sistemlerinde bulunan Kişisel Veri’lere ilişkin olarak bu verilerin toplanma amacının ortadan kalkması ve hukuki saklama sürelerinin sona ermesi halinde tüm verilerin mevzuata uygun şekilde İmha’sından sorumludur.<br /> Kişisel Veri’lerin silinmesi, yok edilmesi ve anonim hale getirilmesiyle ilgili yapılan bütün işlemler kayıt altına alınacaktır ve söz konusu kayıtlar, diğer hukuki yükümlülükler hariç olmak üzere en az üç (3) yıl süreyle saklanacaktır.<br />d. Verar Kargo; işlediği Kişisel Veriler’in doğru ve gerektiğinde güncel olmasını sağlamak için gerekli tedbirleri almaktadır.</p>
                <p><br /><br /></p>
                <p><strong>6- KİŞİSEL VERİLERİN İŞLENMESİ :</strong><br />Kişisel veriler, veri sahibine yapılacak bilgilendirme sonrası ve veri sahibinin açık rıza vermesi halinde işlenecektir. Aydınlatma Yükümlülüğü çerçevesinde açık rıza almadan önce veri sahibine hakları bildirilecek olup açık rıza, KVK Düzenlemelerine uygun yöntemlerle alınacaktır.</p>
                <p>KVK düzenlemeleri kapsamında açık rıza alınmaksızın kişisel verilerin işlenmesinin öngörüldüğü durumlarda (KVK Kanunu Madde 5.2 ve Madde 6.3), Verar Kargo, veri sahibinin açık rızasını almaksızın kişisel verileri işleyebilecektir. Bu bağlamda:</p>
                <p>a. Kanunlarda açıkça öngörülmüş olması halinde,<br />b. Kişisel verilerin işlenmesi Verar Kargo’nun hukuki yükümlülüğünü yerine getirmesi için zorunluysa,<br />c. Bir sözleşmenin kurulması, uygulanması, ifası veya sonlandırılmasıyla doğrudan doğruya ilgili olması kaydıyla, sözleşmenin taraflarına ait kişisel verilerin işlenmesinin gerekli olması halinde,<br />d. Kişisel verilerin açık rıza alınmadan işlenmesi bir hakkın tesisi, kullanılması veya korunması için zorunlu olması halinde,<br />e. Veri sahibinin temel hak ve özgürlüklerine zarar vermemek kaydıyla, Verar Kargo’nun meşru menfaatleri için veri işlenmesinin zorunlu olması halinde,<br />f. Fiili imkânsızlık nedeniyle rızasını açıklayamayacak durumda bulunan veya rızasına hukuki geçerlilik tanınmayan veri sahibinin ve/veya veri sahibi dışındaki bir kişinin hayatının veya beden bütünlüğünün korunması halinde,<br />g. Veri sahibi tarafından kişisel verilerin alenileştirilmiş olması halinde,</p>
                <p>Kişisel veriler Verar Kargo tarafından açık rıza olmaksızın işlenebilir.</p>
                <p><br /><br /></p>
                <p><strong>7- ÖZEL NİTELİKLİ KİŞİSEL VERİLERİN İŞLENMESİ :</strong><br />Verar Kargo, kişilerin ırkı, etnik kökeni, siyasi düşüncesi, felsefi inancı, dini, mezhebi veya diğer inançları, kılık ve kıyafeti, dernek, vakıf ya da sendika üyeliği, sağlığı, cinsel hayatı, ceza mahkûmiyeti ve güvenlik tedbirleriyle ilgili verileri ile biyometrik ve genetik verileri özel nitelikli kişisel verileri, veri sahibinin açık rızası ile işlemektedir.<br />Sağlık ve cinsel hayat dışındaki özel nitelikli kişisel veriler, kanunlarda öngörülen hâllerde ilgili kişinin açık rızası aranmaksızın işlenebilir.<br />Sağlık ve cinsel hayata ilişkin özel nitelikli kişisel veriler ise ancak kamu sağlığının korunması, koruyucu hekimlik, tıbbî teşhis, tedavi ve bakım hizmetlerinin yürütülmesi, sağlık hizmetleri ile finansmanının planlanması ve yönetimi amacıyla, sır saklama yükümlülüğü altında bulunan kişiler veya yetkili kurum ve kuruluşlar tarafından ilgilinin açık rızası aranmaksızın işlenebilir. Örneğin, engelli çalıştırma zorunluluğu kapsamında işyerinde bu statüde çalıştırdığı kişilere ilişkin rapor ve belgelerin işlenmesi.<br />Verar Kargo, özel nitelikli kişisel verilerin işlenmesinde Kurul tarafından belirlenen önlemlerin alınması konusunda gerekli işlemleri yürütmektedir.</p>
                <p><br /><br /></p>
                <p><strong>8- KİŞİSEL VERİLERİN AKTARILMASI :</strong><br />Kişisel Veri’ler yalnızca İlgili Kişi’nin veri aktarımına Açık Rıza’sının bulunması veya Kişisel Verilerin İşlenmesi bölümünde sayılan Açık Rıza’nın aranmadığı hallerden birinin varlığı halinde Türkiye’de bulunan üçüncü kişilere aktarılabilir.<br />Kişisel Veri’lerin Yurtdışı’nda bulunan üçüncü kişilere aktarılmasında ise yukarıda sayılan koşullara ek olarak;<br />• Kişisel Veri’lerin aktarıldığı yabancı ülkenin yeterli seviyede koruma sağlaması ya da;<br />• ilgili yabancı ülkede yeterli korumanın bulunmaması durumunda Verar Kargo’nun ve ilgili yabancı ülkedeki veri sorumlularının yeterli korumanın sağlandığını yazılı olarak taahhüt etmeleri ve Kurul’un izninin bulunması,<br />şartları bulunmalıdır.</p>
                <p><br /><br /></p>
                <p><strong>9- KİŞİSEL VERİLERİN SİLİNMESİ, YOK EDİLMESİ VEYA ANONİM HÂLE GETİRİLMESİ :</strong><br />Verar Kargo, Kanun ve ilgili diğer kanun hükümlerine uygun olarak işlenmiş olmasına rağmen, işlenmesini gerektiren sebeplerin ortadan kalkması hâlinde kişisel veriler resen veya ilgili kişinin talebi üzerine silmekte, yok etmekte veya anonim hâle getirmektedir.</p>
                <p>Kişisel veriler, tekrar kullanılamayacak ve geri getirilemeyecek şekilde silinmekte ve imhası gerçekleştirilmektedir. Buna göre veriler, kayıtlı oldukları evrak, dosya, CD, disket, hard disk gibi araçlardan geri dönüştürülemeyecek şekilde silinmektedir.</p>
                <p><br /><br /></p>
                <p><strong>10- KİŞİSEL VERİ SAHİBİNİ AYDINLATMA YÜKÜMLÜLÜĞÜ :</strong><br />Verar Kargo, KVK Kanunu’nun 10. Maddesine uygun olarak kişisel verilerin elde edilmesi sırasında verileri işlenecek kişileri, verilerinin ne şekilde işleneceği konusunda aydınlatacaktır. KVK Kanunu’nda bilgilendirmede yer alması gereken asgari hususlar sayılmıştır:<br />1. Veri sorumlusu olarak Şirket’in ve varsa temsilcisinin kimliği,<br />2. Kişisel verilerin hangi amaçla işleneceği,<br />3. İşlenen kişisel verilerin kimlere ve hangi amaçla aktarılabileceği,<br />4. Kişisel veri toplamanın yöntemi ve hukuki sebepleri,<br />5. Kişisel veri sahibinin sahip olduğu haklar<br />a. Herhangi bir Kişisel Veri/Kişisel Veriler’inizin işlenip işlenmediğini öğrenme, <br />b. Kişisel Veri/Kişisel Veriler’inizin işlenme faaliyetlerine ilişkin olarak bilgi talep etme,<br />c. Kişisel Veri/Kişisel Veriler’inizin işlenme amaçlarını öğrenme,<br />d. Kişisel Veri/Kişisel Veriler’inizin yurt içinde veya yurt dışında üçüncü kişi/kurum ve/veya kuruluşa aktarılmış olması durumunda bu kişileri/kurum ve/veya kuruluşları öğrenme,<br />e. Kişisel Veri/Kişisel Veriler’inizin eksik veya yanlış işlenmiş olması halinde bunların düzeltilmesini/güncellenmesini isteme,<br />f. Kişisel Veri/Kişisel Veriler’inizin işlenmesini gerektiren sebeplerin ortadan kalkması veya Verar Kargo’nun söz konusu verileri işleyebilmek için hukuki dayanağı veya meşru menfaatinin bulunmaması halinde Kişisel Veri/Kişisel Veriler’inizin silinmesini veya yok edilmesini isteme,<br />g. Kişisel Veri/Kişisel Veriler’inizin otomatik sistemler vasıtasıyla işlenmesi sonucu ortaya çıkabilecek aleyhte sonuçlara itiraz etme ve,<br />h. Kişisel Veri/Kişisel Veriler’inizin kanuna aykırı bir şekilde işlenmesi sebebiyle zarara uğramanız halinde bu zararın tazmin edilmesini isteme</p>
                <p>Veri sahipleri haklarını kullanmak istediği durumlarda taleplerini aşağıda belirtilen ve zaman zaman değişebilecek olan e-posta adresine güvenli elektronik imzalı olarak veya yine aşağıda yer alan ve zaman zaman değişebilecek olan posta adresine kimliklerini tespit edici belgeler ile ıslak imzalı bir dilekçe ile elden teslim edebilir ya da noter aracılığıyla gönderebilir.</p>
                <p>Veri Sorumlusu : Verar Kargo L.T.D.<br />E-posta : <a href="mailto:kvkk@verarkargo.com.tr" class="__cf_email__" data-cfemail="a7c4d4e7d7d3d489c9c2d3">verarkargo.com.tr</a><br />Posta : Mahmutbey, Akdemir Sk. No:24, 34218 Bağcılar / İstanbul<br /> <br />Verar Kargo, talebin niteliğine göre ilgili talebi en kısa sürede ve en geç otuz gün içerisinde ücretsiz olarak sonuçlandıracaktır. Talebe konu işlemlerin bir maliyet gerektirmesi halinde, Kişisel Verilerin Korunması Kurulu tarafından, 6698 Sayılı Kişisel Verilerin Korunması Kanunu’nun 13. Maddesine göre belirlenen tarife üzerinden ücret ve masraf talep edilmesi mümkündür.</p>
                <p>Değerlendirme sonucunda Verar Kargo başvuruları kabul ederek gereken aksiyonları alabileceği gibi başvuruları gerekçeli olarak elektronik posta veya posta yolu ile reddedebilir. Kişisel veri sahibi, başvurusunun reddedilmesi, verilen cevabı yetersiz bulması veya süresinde başvuruya cevap verilmemesi hallerinde 30 gün içerisinde KVK Kurulu’na şikayette bulunabilir.</p>
                <p><br /><br /></p>
                <p><br /><strong>11- POLİTİKADA YAPILACAK DEĞİŞİKLİKLER VE YÜRÜRLÜK TARİHİ :</strong><br />Bu Politikada yer alan hükümler Verar Kargo tarafından gerek görüldüğü takdirde mevzuat hükümlerine uygun olarak internet sitelerinde yayınlanmak suretiyle değiştirebilir. İşbu hükümlerinden herhangi birisinin değişmesi halinde ilgili değişiklikler, değişikliğin yayınlandığı tarihte yürürlüğe girer.<br />İşbu Politika Ocak 2020 tarihinde yayınlanarak yürürlüğe girmiştir.</p>
                <p></p>
            </div>
        </div>
    </div>
@endsection
